// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/mdelillo/apartment-alert/parser (interfaces: Fetcher)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Fetcher interface
type MockFetcher struct {
	ctrl     *gomock.Controller
	recorder *_MockFetcherRecorder
}

// Recorder for MockFetcher (not exported)
type _MockFetcherRecorder struct {
	mock *MockFetcher
}

func NewMockFetcher(ctrl *gomock.Controller) *MockFetcher {
	mock := &MockFetcher{ctrl: ctrl}
	mock.recorder = &_MockFetcherRecorder{mock}
	return mock
}

func (_m *MockFetcher) EXPECT() *_MockFetcherRecorder {
	return _m.recorder
}

func (_m *MockFetcher) Fetch(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "Fetch", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFetcherRecorder) Fetch(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Fetch", arg0)
}
